# Pipeline Medallion — ANS Beneficiários SP

Versão notebook (estilo Databricks) do pipeline. Executa **Bronze → Silver → Gold** e as **3 consultas** do case.

> O mesmo código roda no Databricks: basta apontar `LAKE_ROOT` para o S3 real. Aqui usamos MinIO (S3 local) via Docker.

In [1]:
import sys
sys.path.append('/app')

from src.config import get_spark, sql_params
from src.sql_runner import run_sql_file
from src.queries import run_queries

spark = get_spark('case-ans-notebook')
params = sql_params()
params

Warning: Ignoring non-Spark config property: javax.jdo.option.ConnectionURL

:: loading settings :: url = jar:file:/usr/local/lib/python3.11/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml

Ivy Default Cache set to: /root/.ivy2/cache
The jars for the packages stored in: /root/.ivy2/jars
io.delta#delta-spark_2.12 added as a dependency
org.apache.hadoop#hadoop-aws added as a dependency
com.amazonaws#aws-java-sdk-bundle added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-f653950f-f0a1-4d4b-9753-d1e2b8c740ce;1.0
	confs: [default]
	found io.delta#delta-spark_2.12;3.2.0 in central
	found io.delta#delta-storage;3.2.0 in central
	found org.antlr#antlr4-runtime;4.9.3 in central
	found org.apache.hadoop#hadoop-aws;3.3.4 in central
	found com.amazonaws#aws-java-sdk-bundle;1.12.262 in central
	found org.wildfly.openssl#wildfly-openssl;1.0.7.Final in central
:: resolution report :: resolve 206ms :: artifacts dl 10ms
	:: modules in use:
	com.amazonaws#aws-java-sdk-bundle;1.12.262 from central in [default]
	io.delta#delta-spark_2.12;3.2.0 from central in [default]
	io.delta#delta-storage;3.2.0 from central in [default]
	org.antlr#antlr4-runtime;4.9.3 from central in [default]
	org.apache.hadoop#hadoop-aws;3.3.4 from central in [default]
	org.wildfly.openssl#wildfly-openssl;1.0.7.Final from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   6   |   0   |   0   |   0   ||   6   |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-f653950f-f0a1-4d4b-9753-d1e2b8c740ce
	confs: [default]
	0 artifacts copied, 6 already retrieved (0kB/5ms)
26/08/02 05:24:13 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).

{'LAKE_ROOT': 's3a://lakehouse',
 'CSV_PATH': '/app/data/pda-024-icb-SP-2025_08.csv'}

## Bronze — ingestão as-is
Carrega o CSV bruto para Delta, preservando a estrutura original.

In [2]:
run_sql_file(spark, '00_bronze.sql', params)
spark.table('bronze.beneficiarios').limit(5).toPandas()

=== 00_bronze.sql  (3 statements) ===
  [1/3] CREATE DATABASE IF NOT EXISTS bronze LOCATION 's3a://lakehouse/bronze'...

26/08/02 05:24:19 WARN HiveConf: HiveConf of name hive.stats.jdbc.timeout does not exist
26/08/02 05:24:19 WARN HiveConf: HiveConf of name hive.stats.retries.wait does not exist
26/08/02 05:25:03 WARN ObjectStore: Version information not found in metastore. hive.metastore.schema.verification is not enabled so recording the schema version 2.3.0
26/08/02 05:25:03 WARN ObjectStore: setMetaStoreSchemaVersion called but recording version is disabled: version = 2.3.0, comment = Set by MetaStore UNKNOWN@172.30.0.8
26/08/02 05:25:03 WARN ObjectStore: Failed to get database default, returning NoSuchObjectException
26/08/02 05:25:07 WARN ObjectStore: Failed to get database bronze, returning NoSuchObjectException
26/08/02 05:25:07 WARN ObjectStore: Failed to get database bronze, returning NoSuchObjectException
26/08/02 05:25:07 WARN ObjectStore: Failed to get database global_temp, returning NoSuchObjectException
26/08/02 05:25:07 WARN ObjectStore: Failed to get database bronze, returning NoSuchObjectException
26/08/02 05:25:07 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties

  [2/3] CREATE OR REPLACE TEMPORARY VIEW raw_csv USING csv OPTIONS ( path '/app/data/pda...
  [3/3] CREATE OR REPLACE TABLE bronze.beneficiarios USING delta AS SELECT *, current_ti...

26/08/02 05:25:30 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.
26/08/02 05:25:32 WARN OptimisticTransaction: [tableId=af61115d,txnId=29cee5a6] Change in the table id detected in txn. Table id for txn on table at s3a://lakehouse/bronze/beneficiarios was af61115d-4d6b-434a-81ee-53c23b9d2efc when the txn was created and is now changed to 55956880-d82c-4475-a963-62764dbaa9cd.
26/08/02 05:25:33 WARN DeltaLog: Change in the table id detected while updating snapshot.
Previous snapshot = Snapshot(path=s3a://lakehouse/bronze/beneficiarios/_delta_log, version=4, metadata=Metadata(af61115d-4d6b-434a-81ee-53c23b9d2efc,null,null,Format(parquet,Map()),{"type":"struct","fields":[{"name":"ID_CMPT_MOVEL","type":"string","nullable":true,"metadata":{}},{"name":"CD_OPERADORA","type":"string","nullable":true,"metadata":{}},{"name":"NM_RAZAO_SOCIAL","type":"string","nullable":true,"metadata":{}},{"name":"NR_CNPJ","type":"string","nullable":true,"metadata":{}},{"name":"MODALIDADE_OPERADORA","type":"string","nullable":true,"metadata":{}},{"name":"SG_UF","type":"string","nullable":true,"metadata":{}},{"name":"CD_MUNICIPIO","type":"string","nullable":true,"metadata":{}},{"name":"NM_MUNICIPIO","type":"string","nullable":true,"metadata":{}},{"name":"TP_SEXO","type":"string","nullable":true,"metadata":{}},{"name":"DE_FAIXA_ETARIA","type":"string","nullable":true,"metadata":{}},{"name":"DE_FAIXA_ETARIA_REAJ","type":"string","nullable":true,"metadata":{}},{"name":"CD_PLANO","type":"string","nullable":true,"metadata":{}},{"name":"TP_VIGENCIA_PLANO","type":"string","nullable":true,"metadata":{}},{"name":"DE_CONTRATACAO_PLANO","type":"string","nullable":true,"metadata":{}},{"name":"DE_SEGMENTACAO_PLANO","type":"string","nullable":true,"metadata":{}},{"name":"DE_ABRG_GEOGRAFICA_PLANO","type":"string","nullable":true,"metadata":{}},{"name":"COBERTURA_ASSIST_PLAN","type":"string","nullable":true,"metadata":{}},{"name":"TIPO_VINCULO","type":"string","nullable":true,"metadata":{}},{"name":"QT_BENEFICIARIO_ATIVO","type":"string","nullable":true,"metadata":{}},{"name":"QT_BENEFICIARIO_ADERIDO","type":"string","nullable":true,"metadata":{}},{"name":"QT_BENEFICIARIO_CANCELADO","type":"string","nullable":true,"metadata":{}},{"name":"DT_CARGA","type":"string","nullable":true,"metadata":{}},{"name":"_ingested_at","type":"timestamp","nullable":true,"metadata":{}},{"name":"_source_file","type":"string","nullable":true,"metadata":{}}]},List(),Map(),Some(1785647432096)), logSegment=LogSegment(s3a://lakehouse/bronze/beneficiarios/_delta_log,4,WrappedArray(S3AFileStatus{path=s3a://lakehouse/bronze/beneficiarios/_delta_log/00000000000000000000.json; isDirectory=false; length=30985; replication=1; blocksize=33554432; modification_time=1785640140074; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=5e95bde411880a60312110fde07a6614 versionId=null, S3AFileStatus{path=s3a://lakehouse/bronze/beneficiarios/_delta_log/00000000000000000001.json; isDirectory=false; length=33210; replication=1; blocksize=33554432; modification_time=1785644713926; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=f50eaf1745e9f7117f2e6746537f6ef7 versionId=null, S3AFileStatus{path=s3a://lakehouse/bronze/beneficiarios/_delta_log/00000000000000000002.json; isDirectory=false; length=33210; replication=1; blocksize=33554432; modification_time=1785644831907; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=1c16bf6e006b5b6483b77680c4e2633c versionId=null, S3AFileStatus{path=s3a://lakehouse/bronze/beneficiarios/_delta_log/00000000000000000003.json; isDirectory=false; length=33210; replication=1; blocksize=33554432; modification_time=1785645975593; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=b4677cf6717379ee82be3e34f110ebcf versionId=null, S3AFileStatus{path=s3a://lakehouse/bronze/beneficiarios/_delta_log/00000000000000000004.json; isDirectory=false; length=33210; replication=1; blocksize=33554432; modification_time=1785647453176; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=eb28b5632bf369744e5b4b05f5048532 versionId=null),org.apache.spark.sql.delta.EmptyCheckpointProvider$@287b4d2d,1785647453176), checksumOpt=None)
New snapshot = Snapshot(path=s3a://lakehouse/bronze/beneficiarios/_delta_log, version=5, metadata=Metadata(55956880-d82c-4475-a963-62764dbaa9cd,null,null,Format(parquet,Map()),{"type":"struct","fields":[{"name":"ID_CMPT_MOVEL","type":"string","nullable":true,"metadata":{}},{"name":"CD_OPERADORA","type":"string","nullable":true,"metadata":{}},{"name":"NM_RAZAO_SOCIAL","type":"string","nullable":true,"metadata":{}},{"name":"NR_CNPJ","type":"string","nullable":true,"metadata":{}},{"name":"MODALIDADE_OPERADORA","type":"string","nullable":true,"metadata":{}},{"name":"SG_UF","type":"string","nullable":true,"metadata":{}},{"name":"CD_MUNICIPIO","type":"string","nullable":true,"metadata":{}},{"name":"NM_MUNICIPIO","type":"string","nullable":true,"metadata":{}},{"name":"TP_SEXO","type":"string","nullable":true,"metadata":{}},{"name":"DE_FAIXA_ETARIA","type":"string","nullable":true,"metadata":{}},{"name":"DE_FAIXA_ETARIA_REAJ","type":"string","nullable":true,"metadata":{}},{"name":"CD_PLANO","type":"string","nullable":true,"metadata":{}},{"name":"TP_VIGENCIA_PLANO","type":"string","nullable":true,"metadata":{}},{"name":"DE_CONTRATACAO_PLANO","type":"string","nullable":true,"metadata":{}},{"name":"DE_SEGMENTACAO_PLANO","type":"string","nullable":true,"metadata":{}},{"name":"DE_ABRG_GEOGRAFICA_PLANO","type":"string","nullable":true,"metadata":{}},{"name":"COBERTURA_ASSIST_PLAN","type":"string","nullable":true,"metadata":{}},{"name":"TIPO_VINCULO","type":"string","nullable":true,"metadata":{}},{"name":"QT_BENEFICIARIO_ATIVO","type":"string","nullable":true,"metadata":{}},{"name":"QT_BENEFICIARIO_ADERIDO","type":"string","nullable":true,"metadata":{}},{"name":"QT_BENEFICIARIO_CANCELADO","type":"string","nullable":true,"metadata":{}},{"name":"DT_CARGA","type":"string","nullable":true,"metadata":{}},{"name":"_ingested_at","type":"timestamp","nullable":true,"metadata":{}},{"name":"_source_file","type":"string","nullable":true,"metadata":{}}]},List(),Map(),Some(1785648311200)), logSegment=LogSegment(s3a://lakehouse/bronze/beneficiarios/_delta_log,5,ArrayBuffer(S3AFileStatus{path=s3a://lakehouse/bronze/beneficiarios/_delta_log/00000000000000000000.json; isDirectory=false; length=30985; replication=1; blocksize=33554432; modification_time=1785640140074; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=5e95bde411880a60312110fde07a6614 versionId=null, S3AFileStatus{path=s3a://lakehouse/bronze/beneficiarios/_delta_log/00000000000000000001.json; isDirectory=false; length=33210; replication=1; blocksize=33554432; modification_time=1785644713926; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=f50eaf1745e9f7117f2e6746537f6ef7 versionId=null, S3AFileStatus{path=s3a://lakehouse/bronze/beneficiarios/_delta_log/00000000000000000002.json; isDirectory=false; length=33210; replication=1; blocksize=33554432; modification_time=1785644831907; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=1c16bf6e006b5b6483b77680c4e2633c versionId=null, S3AFileStatus{path=s3a://lakehouse/bronze/beneficiarios/_delta_log/00000000000000000003.json; isDirectory=false; length=33210; replication=1; blocksize=33554432; modification_time=1785645975593; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=b4677cf6717379ee82be3e34f110ebcf versionId=null, S3AFileStatus{path=s3a://lakehouse/bronze/beneficiarios/_delta_log/00000000000000000004.json; isDirectory=false; length=33210; replication=1; blocksize=33554432; modification_time=1785647453176; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=eb28b5632bf369744e5b4b05f5048532 versionId=null, S3AFileStatus{path=s3a://lakehouse/bronze/beneficiarios/_delta_log/00000000000000000005.json; isDirectory=false; length=33210; replication=1; blocksize=33554432; modification_time=1785648333000; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=799cb147d951e151d1349d659e4be9c4 versionId=null),org.apache.spark.sql.delta.EmptyCheckpointProvider$@287b4d2d,1785648333000), checksumOpt=None).
26/08/02 05:25:33 WARN HiveExternalCatalog: Couldn't find corresponding Hive SerDe for data source provider delta. Persisting data source table `spark_catalog`.`bronze`.`beneficiarios` into Hive metastore in Spark SQL specific format, which is NOT compatible with Hive.
26/08/02 05:25:33 WARN SessionState: METASTORE_FILTER_HOOK will be ignored, since hive.security.authorization.manager is set to instance of HiveAuthorizerFactory.
26/08/02 05:25:33 WARN HiveConf: HiveConf of name hive.internal.ss.authz.settings.applied.marker does not exist
26/08/02 05:25:33 WARN HiveConf: HiveConf of name hive.stats.jdbc.timeout does not exist
26/08/02 05:25:33 WARN HiveConf: HiveConf of name hive.stats.retries.wait does not exist

,ID_CMPT_MOVEL,CD_OPERADORA,NM_RAZAO_SOCIAL,NR_CNPJ,MODALIDADE_OPERADORA,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,TP_SEXO,DE_FAIXA_ETARIA,...,DE_SEGMENTACAO_PLANO,DE_ABRG_GEOGRAFICA_PLANO,COBERTURA_ASSIST_PLAN,TIPO_VINCULO,QT_BENEFICIARIO_ATIVO,QT_BENEFICIARIO_ADERIDO,QT_BENEFICIARIO_CANCELADO,DT_CARGA,_ingested_at,_source_file
0,2025-08,333051,UNIMED DE GUARULHOS COOPERATIVA DE TRABALHO MÉ...,74466137000172,COOPERATIVA MÉDICA,SP,351880,Guarulhos,F,20 a 24 anos,...,Ambulatorial + Hospitalar com obstetrícia,Municipal,Médico-hospitalar,Titular,1,0,0,2026-06-30,2026-08-02 05:25:11.458589,/app/data/pda-024-icb-SP-2025_08.csv
1,2025-08,350249,H.B. SAÚDE S/A.,02668512000156,MEDICINA DE GRUPO,SP,351120,Catiguá,M,30 a 34 anos,...,Ambulatorial + Hospitalar com obstetrícia,Grupo de municípios,Médico-hospitalar,Titular,1,0,0,2026-06-30,2026-08-02 05:25:11.458589,/app/data/pda-024-icb-SP-2025_08.csv
2,2025-08,364312,UNIMED DE ARARAQUARA - COOP. DE TRAB. MÉDICO,45272366000158,COOPERATIVA MÉDICA,SP,350320,Araraquara,F,65 a 69 anos,...,Ambulatorial + Hospitalar com obstetrícia,Grupo de municípios,Médico-hospitalar,Titular,1,0,0,2026-06-30,2026-08-02 05:25:11.458589,/app/data/pda-024-icb-SP-2025_08.csv
3,2025-08,346659,CAIXA DE ASSISTÊNCIA DOS FUNCIONÁRIOS DO BANCO...,33719485000127,AUTOGESTÃO,SP,354980,São José do Rio Preto,M,50 a 54 anos,...,Ambulatorial + Hospitalar com obstetrícia,Nacional,Médico-hospitalar,Titular,3,0,0,2026-06-30,2026-08-02 05:25:11.458589,/app/data/pda-024-icb-SP-2025_08.csv
4,2025-08,379956,CARE PLUS MEDICINA ASSISTENCIAL LTDA.,02725347000127,MEDICINA DE GRUPO,SP,352400,Itupeva,F,30 a 34 anos,...,Ambulatorial + Hospitalar com obstetrícia,Grupo de estados,Médico-hospitalar,Titular,2,0,0,2026-06-30,2026-08-02 05:25:11.458589,/app/data/pda-024-icb-SP-2025_08.csv

## Silver — tipagem + mascaramento
Tipa as colunas, mascara o CNPJ e particiona por competência.

In [3]:
run_sql_file(spark, '01_silver.sql', params)
spark.table('silver.beneficiarios').limit(5).toPandas()

=== 01_silver.sql  (2 statements) ===
  [1/2] CREATE DATABASE IF NOT EXISTS silver LOCATION 's3a://lakehouse/silver'...
  [2/2] CREATE OR REPLACE TABLE silver.beneficiarios USING delta PARTITIONED BY (id_cmpt...

26/08/02 05:26:05 WARN ObjectStore: Failed to get database silver, returning NoSuchObjectException
26/08/02 05:26:05 WARN ObjectStore: Failed to get database silver, returning NoSuchObjectException
26/08/02 05:26:05 WARN ObjectStore: Failed to get database silver, returning NoSuchObjectException
26/08/02 05:26:15 WARN OptimisticTransaction: [tableId=fce75241,txnId=3665729f] Change in the table id detected in txn. Table id for txn on table at s3a://lakehouse/silver/beneficiarios was fce75241-21d2-41e1-99eb-fca18c3d9366 when the txn was created and is now changed to d7fe35cd-5a89-4b7c-88a6-c993b707b1d8.
26/08/02 05:26:16 WARN DeltaLog: Change in the table id detected while updating snapshot.
Previous snapshot = Snapshot(path=s3a://lakehouse/silver/beneficiarios/_delta_log, version=4, metadata=Metadata(fce75241-21d2-41e1-99eb-fca18c3d9366,null,null,Format(parquet,Map()),{"type":"struct","fields":[{"name":"cd_operadora","type":"string","nullable":true,"metadata":{}},{"name":"nm_razao_social","type":"string","nullable":true,"metadata":{}},{"name":"nr_cnpj_masc","type":"string","nullable":true,"metadata":{}},{"name":"modalidade_operadora","type":"string","nullable":true,"metadata":{}},{"name":"sg_uf","type":"string","nullable":true,"metadata":{}},{"name":"cd_municipio","type":"string","nullable":true,"metadata":{}},{"name":"nm_municipio","type":"string","nullable":true,"metadata":{}},{"name":"tp_sexo","type":"string","nullable":true,"metadata":{}},{"name":"de_faixa_etaria","type":"string","nullable":true,"metadata":{}},{"name":"de_segmentacao_plano","type":"string","nullable":true,"metadata":{}},{"name":"de_abrg_geografica_plano","type":"string","nullable":true,"metadata":{}},{"name":"de_contratacao_plano","type":"string","nullable":true,"metadata":{}},{"name":"cobertura_assist_plan","type":"string","nullable":true,"metadata":{}},{"name":"tipo_vinculo","type":"string","nullable":true,"metadata":{}},{"name":"qt_beneficiario_ativo","type":"integer","nullable":true,"metadata":{}},{"name":"qt_beneficiario_aderido","type":"integer","nullable":true,"metadata":{}},{"name":"qt_beneficiario_cancelado","type":"integer","nullable":true,"metadata":{}},{"name":"dt_carga","type":"date","nullable":true,"metadata":{}},{"name":"id_cmpt_movel","type":"string","nullable":true,"metadata":{}}]},List(id_cmpt_movel),Map(),Some(1785647483947)), logSegment=LogSegment(s3a://lakehouse/silver/beneficiarios/_delta_log,4,WrappedArray(S3AFileStatus{path=s3a://lakehouse/silver/beneficiarios/_delta_log/00000000000000000000.json; isDirectory=false; length=10412; replication=1; blocksize=33554432; modification_time=1785640152908; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=09c2bfd298183a6ebbe79104faaa6f3c versionId=null, S3AFileStatus{path=s3a://lakehouse/silver/beneficiarios/_delta_log/00000000000000000001.json; isDirectory=false; length=11386; replication=1; blocksize=33554432; modification_time=1785644762520; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=0469dcbad41a21aa0202836cdeb550b1 versionId=null, S3AFileStatus{path=s3a://lakehouse/silver/beneficiarios/_delta_log/00000000000000000002.json; isDirectory=false; length=11386; replication=1; blocksize=33554432; modification_time=1785644876853; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=359805d22fb0ff2f9a4454d6878b24e9 versionId=null, S3AFileStatus{path=s3a://lakehouse/silver/beneficiarios/_delta_log/00000000000000000003.json; isDirectory=false; length=11386; replication=1; blocksize=33554432; modification_time=1785646022267; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=514c6bd4b888c1fc48e225d9c66207cf versionId=null, S3AFileStatus{path=s3a://lakehouse/silver/beneficiarios/_delta_log/00000000000000000004.json; isDirectory=false; length=11386; replication=1; blocksize=33554432; modification_time=1785647499036; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=d3ed22c8ac9e40f749d78f34501f04bc versionId=null),org.apache.spark.sql.delta.EmptyCheckpointProvider$@287b4d2d,1785647499036), checksumOpt=None)
New snapshot = Snapshot(path=s3a://lakehouse/silver/beneficiarios/_delta_log, version=5, metadata=Metadata(d7fe35cd-5a89-4b7c-88a6-c993b707b1d8,null,null,Format(parquet,Map()),{"type":"struct","fields":[{"name":"cd_operadora","type":"string","nullable":true,"metadata":{}},{"name":"nm_razao_social","type":"string","nullable":true,"metadata":{}},{"name":"nr_cnpj_masc","type":"string","nullable":true,"metadata":{}},{"name":"modalidade_operadora","type":"string","nullable":true,"metadata":{}},{"name":"sg_uf","type":"string","nullable":true,"metadata":{}},{"name":"cd_municipio","type":"string","nullable":true,"metadata":{}},{"name":"nm_municipio","type":"string","nullable":true,"metadata":{}},{"name":"tp_sexo","type":"string","nullable":true,"metadata":{}},{"name":"de_faixa_etaria","type":"string","nullable":true,"metadata":{}},{"name":"de_segmentacao_plano","type":"string","nullable":true,"metadata":{}},{"name":"de_abrg_geografica_plano","type":"string","nullable":true,"metadata":{}},{"name":"de_contratacao_plano","type":"string","nullable":true,"metadata":{}},{"name":"cobertura_assist_plan","type":"string","nullable":true,"metadata":{}},{"name":"tipo_vinculo","type":"string","nullable":true,"metadata":{}},{"name":"qt_beneficiario_ativo","type":"integer","nullable":true,"metadata":{}},{"name":"qt_beneficiario_aderido","type":"integer","nullable":true,"metadata":{}},{"name":"qt_beneficiario_cancelado","type":"integer","nullable":true,"metadata":{}},{"name":"dt_carga","type":"date","nullable":true,"metadata":{}},{"name":"id_cmpt_movel","type":"string","nullable":true,"metadata":{}}]},List(id_cmpt_movel),Map(),Some(1785648365890)), logSegment=LogSegment(s3a://lakehouse/silver/beneficiarios/_delta_log,5,ArrayBuffer(S3AFileStatus{path=s3a://lakehouse/silver/beneficiarios/_delta_log/00000000000000000000.json; isDirectory=false; length=10412; replication=1; blocksize=33554432; modification_time=1785640152908; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=09c2bfd298183a6ebbe79104faaa6f3c versionId=null, S3AFileStatus{path=s3a://lakehouse/silver/beneficiarios/_delta_log/00000000000000000001.json; isDirectory=false; length=11386; replication=1; blocksize=33554432; modification_time=1785644762520; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=0469dcbad41a21aa0202836cdeb550b1 versionId=null, S3AFileStatus{path=s3a://lakehouse/silver/beneficiarios/_delta_log/00000000000000000002.json; isDirectory=false; length=11386; replication=1; blocksize=33554432; modification_time=1785644876853; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=359805d22fb0ff2f9a4454d6878b24e9 versionId=null, S3AFileStatus{path=s3a://lakehouse/silver/beneficiarios/_delta_log/00000000000000000003.json; isDirectory=false; length=11386; replication=1; blocksize=33554432; modification_time=1785646022267; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=514c6bd4b888c1fc48e225d9c66207cf versionId=null, S3AFileStatus{path=s3a://lakehouse/silver/beneficiarios/_delta_log/00000000000000000004.json; isDirectory=false; length=11386; replication=1; blocksize=33554432; modification_time=1785647499036; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=d3ed22c8ac9e40f749d78f34501f04bc versionId=null, S3AFileStatus{path=s3a://lakehouse/silver/beneficiarios/_delta_log/00000000000000000005.json; isDirectory=false; length=11386; replication=1; blocksize=33554432; modification_time=1785648375000; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=0913fa5c66b31b67a648d9b6f5853acc versionId=null),org.apache.spark.sql.delta.EmptyCheckpointProvider$@287b4d2d,1785648375000), checksumOpt=None).
26/08/02 05:26:16 WARN HiveExternalCatalog: Couldn't find corresponding Hive SerDe for data source provider delta. Persisting data source table `spark_catalog`.`silver`.`beneficiarios` into Hive metastore in Spark SQL specific format, which is NOT compatible with Hive.

,cd_operadora,nm_razao_social,nr_cnpj_masc,modalidade_operadora,sg_uf,cd_municipio,nm_municipio,tp_sexo,de_faixa_etaria,de_segmentacao_plano,de_abrg_geografica_plano,de_contratacao_plano,cobertura_assist_plan,tipo_vinculo,qt_beneficiario_ativo,qt_beneficiario_aderido,qt_beneficiario_cancelado,dt_carga,id_cmpt_movel
0,000582,PORTO SEGURO - SEGURO SAÚDE S/A,04540010******,SEGURADORA ESPECIALIZADA EM SAÚDE,SP,355100,São Vicente,M,20 a 24 anos,Odontológico,Nacional,Coletivo Empresarial,Odontológico,Titular,14,0,1,2026-06-30,2025-08
1,355721,UNIMED DE SANTOS COOP DE TRAB MEDICO,58229691******,COOPERATIVA MÉDICA,SP,354100,Praia Grande,F,65 a 69 anos,Ambulatorial + Hospitalar com obstetrícia,Grupo de municípios,Individual ou Familiar,Médico-hospitalar,Dependente,1,0,0,2026-06-30,2025-08
2,312126,FUNDAÇÃO SAÚDE ITAÚ,73809352******,AUTOGESTÃO,SP,350900,Caieiras,M,35 a 39 anos,Ambulatorial + Hospitalar com obstetrícia,Nacional,Coletivo Empresarial,Médico-hospitalar,Titular,1,0,0,2026-06-30,2025-08
3,419419,BRASILDENTAL OPERADORA DE PLANOS ODONTOLÓGICOS...,19962272******,ODONTOLOGIA DE GRUPO,SP,350600,Bauru,M,35 a 39 anos,Odontológico,Nacional,Coletivo Empresarial,Odontológico,Titular,10,0,0,2026-06-30,2025-08
4,312924,CAIXA ECONÔMICA FEDERAL,00360305******,AUTOGESTÃO,SP,350370,Ariranha,F,40 a 44 anos,Ambulatorial + Hospitalar com obstetrícia + Od...,Nacional,Coletivo por Adesão,Médico-hospitalar,Titular,1,0,0,2026-06-30,2025-08

## Gold — tabelas curadas
Agrega os dados para consumo analítico.

In [4]:
run_sql_file(spark, '02_gold.sql', params)
spark.sql('SHOW TABLES IN gold').toPandas()

=== 02_gold.sql  (4 statements) ===
  [1/4] CREATE DATABASE IF NOT EXISTS gold LOCATION 's3a://lakehouse/gold'...
  [2/4] CREATE OR REPLACE TABLE gold.beneficiarios_por_operadora USING delta AS SELECT c...

26/08/02 05:27:47 WARN ObjectStore: Failed to get database gold, returning NoSuchObjectException
26/08/02 05:27:47 WARN ObjectStore: Failed to get database gold, returning NoSuchObjectException
26/08/02 05:27:47 WARN ObjectStore: Failed to get database gold, returning NoSuchObjectException
26/08/02 05:27:48 WARN OptimisticTransaction: [tableId=92ca826c,txnId=76de63e1] Change in the table id detected in txn. Table id for txn on table at s3a://lakehouse/gold/beneficiarios_por_operadora was 92ca826c-67f0-40bb-8e54-2baec78ffebe when the txn was created and is now changed to 3ebccd36-950c-4eee-adc6-c85917636eed.
26/08/02 05:27:49 WARN DeltaLog: Change in the table id detected while updating snapshot.
Previous snapshot = Snapshot(path=s3a://lakehouse/gold/beneficiarios_por_operadora/_delta_log, version=4, metadata=Metadata(92ca826c-67f0-40bb-8e54-2baec78ffebe,null,null,Format(parquet,Map()),{"type":"struct","fields":[{"name":"cd_operadora","type":"string","nullable":true,"metadata":{}},{"name":"nm_razao_social","type":"string","nullable":true,"metadata":{}},{"name":"qt_beneficiarios_ativos","type":"long","nullable":true,"metadata":{}}]},List(),Map(),Some(1785647521677)), logSegment=LogSegment(s3a://lakehouse/gold/beneficiarios_por_operadora/_delta_log,4,WrappedArray(S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_operadora/_delta_log/00000000000000000000.json; isDirectory=false; length=1537; replication=1; blocksize=33554432; modification_time=1785640155233; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=10078361c0ed319dc567b8e09fdc7585 versionId=null, S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_operadora/_delta_log/00000000000000000001.json; isDirectory=false; length=1700; replication=1; blocksize=33554432; modification_time=1785644792495; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=8b709b82a05e16e5fb4465635065e986 versionId=null, S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_operadora/_delta_log/00000000000000000002.json; isDirectory=false; length=1700; replication=1; blocksize=33554432; modification_time=1785644902893; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=ced47862fe84fb6ac7ca1dd93feb7583 versionId=null, S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_operadora/_delta_log/00000000000000000003.json; isDirectory=false; length=1700; replication=1; blocksize=33554432; modification_time=1785646050525; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=2f40fdc4bba9cc2cbb824113a7fcac86 versionId=null, S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_operadora/_delta_log/00000000000000000004.json; isDirectory=false; length=1700; replication=1; blocksize=33554432; modification_time=1785647528315; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=8a2b65f7740adcbdad8cf86658aab239 versionId=null),org.apache.spark.sql.delta.EmptyCheckpointProvider$@287b4d2d,1785647528315), checksumOpt=None)
New snapshot = Snapshot(path=s3a://lakehouse/gold/beneficiarios_por_operadora/_delta_log, version=5, metadata=Metadata(3ebccd36-950c-4eee-adc6-c85917636eed,null,null,Format(parquet,Map()),{"type":"struct","fields":[{"name":"cd_operadora","type":"string","nullable":true,"metadata":{}},{"name":"nm_razao_social","type":"string","nullable":true,"metadata":{}},{"name":"qt_beneficiarios_ativos","type":"long","nullable":true,"metadata":{}}]},List(),Map(),Some(1785648467370)), logSegment=LogSegment(s3a://lakehouse/gold/beneficiarios_por_operadora/_delta_log,5,ArrayBuffer(S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_operadora/_delta_log/00000000000000000000.json; isDirectory=false; length=1537; replication=1; blocksize=33554432; modification_time=1785640155233; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=10078361c0ed319dc567b8e09fdc7585 versionId=null, S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_operadora/_delta_log/00000000000000000001.json; isDirectory=false; length=1700; replication=1; blocksize=33554432; modification_time=1785644792495; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=8b709b82a05e16e5fb4465635065e986 versionId=null, S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_operadora/_delta_log/00000000000000000002.json; isDirectory=false; length=1700; replication=1; blocksize=33554432; modification_time=1785644902893; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=ced47862fe84fb6ac7ca1dd93feb7583 versionId=null, S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_operadora/_delta_log/00000000000000000003.json; isDirectory=false; length=1700; replication=1; blocksize=33554432; modification_time=1785646050525; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=2f40fdc4bba9cc2cbb824113a7fcac86 versionId=null, S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_operadora/_delta_log/00000000000000000004.json; isDirectory=false; length=1700; replication=1; blocksize=33554432; modification_time=1785647528315; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=8a2b65f7740adcbdad8cf86658aab239 versionId=null, S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_operadora/_delta_log/00000000000000000005.json; isDirectory=false; length=1700; replication=1; blocksize=33554432; modification_time=1785648468000; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=d299ab03e0f31d19602dab2f2d296d0f versionId=null),org.apache.spark.sql.delta.EmptyCheckpointProvider$@287b4d2d,1785648468000), checksumOpt=None).
26/08/02 05:27:49 WARN HiveExternalCatalog: Couldn't find corresponding Hive SerDe for data source provider delta. Persisting data source table `spark_catalog`.`gold`.`beneficiarios_por_operadora` into Hive metastore in Spark SQL specific format, which is NOT compatible with Hive.

  [3/4] CREATE OR REPLACE TABLE gold.beneficiarios_por_faixa_etaria USING delta AS SELEC...

26/08/02 05:27:50 WARN OptimisticTransaction: [tableId=82c90346,txnId=bb9f7a7a] Change in the table id detected in txn. Table id for txn on table at s3a://lakehouse/gold/beneficiarios_por_faixa_etaria was 82c90346-bf38-4d7b-a47c-3295aedaeb46 when the txn was created and is now changed to c110cbae-3a3e-44bb-9e90-11d90c450c4a.
26/08/02 05:27:50 WARN DeltaLog: Change in the table id detected while updating snapshot.
Previous snapshot = Snapshot(path=s3a://lakehouse/gold/beneficiarios_por_faixa_etaria/_delta_log, version=4, metadata=Metadata(82c90346-bf38-4d7b-a47c-3295aedaeb46,null,null,Format(parquet,Map()),{"type":"struct","fields":[{"name":"de_faixa_etaria","type":"string","nullable":true,"metadata":{}},{"name":"qt_beneficiarios_ativos","type":"long","nullable":true,"metadata":{}}]},List(),Map(),Some(1785647529118)), logSegment=LogSegment(s3a://lakehouse/gold/beneficiarios_por_faixa_etaria/_delta_log,4,WrappedArray(S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_faixa_etaria/_delta_log/00000000000000000000.json; isDirectory=false; length=1341; replication=1; blocksize=33554432; modification_time=1785640156320; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=fbb7eb8a52f2e4d53f1f07e63b9605bc versionId=null, S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_faixa_etaria/_delta_log/00000000000000000001.json; isDirectory=false; length=1503; replication=1; blocksize=33554432; modification_time=1785644795820; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=07220c1547bef066067ea96c61373412 versionId=null, S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_faixa_etaria/_delta_log/00000000000000000002.json; isDirectory=false; length=1503; replication=1; blocksize=33554432; modification_time=1785644905255; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=f4393f6dac56361c9d7260b5c27faab9 versionId=null, S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_faixa_etaria/_delta_log/00000000000000000003.json; isDirectory=false; length=1503; replication=1; blocksize=33554432; modification_time=1785646053423; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=2da1e1428f7f8f72ba2b9a1da7f732ff versionId=null, S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_faixa_etaria/_delta_log/00000000000000000004.json; isDirectory=false; length=1503; replication=1; blocksize=33554432; modification_time=1785647531136; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=0e629bb8c1b89ea411ec8fb2a5b4fead versionId=null),org.apache.spark.sql.delta.EmptyCheckpointProvider$@287b4d2d,1785647531136), checksumOpt=None)
New snapshot = Snapshot(path=s3a://lakehouse/gold/beneficiarios_por_faixa_etaria/_delta_log, version=5, metadata=Metadata(c110cbae-3a3e-44bb-9e90-11d90c450c4a,null,null,Format(parquet,Map()),{"type":"struct","fields":[{"name":"de_faixa_etaria","type":"string","nullable":true,"metadata":{}},{"name":"qt_beneficiarios_ativos","type":"long","nullable":true,"metadata":{}}]},List(),Map(),Some(1785648469332)), logSegment=LogSegment(s3a://lakehouse/gold/beneficiarios_por_faixa_etaria/_delta_log,5,ArrayBuffer(S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_faixa_etaria/_delta_log/00000000000000000000.json; isDirectory=false; length=1341; replication=1; blocksize=33554432; modification_time=1785640156320; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=fbb7eb8a52f2e4d53f1f07e63b9605bc versionId=null, S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_faixa_etaria/_delta_log/00000000000000000001.json; isDirectory=false; length=1503; replication=1; blocksize=33554432; modification_time=1785644795820; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=07220c1547bef066067ea96c61373412 versionId=null, S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_faixa_etaria/_delta_log/00000000000000000002.json; isDirectory=false; length=1503; replication=1; blocksize=33554432; modification_time=1785644905255; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=f4393f6dac56361c9d7260b5c27faab9 versionId=null, S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_faixa_etaria/_delta_log/00000000000000000003.json; isDirectory=false; length=1503; replication=1; blocksize=33554432; modification_time=1785646053423; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=2da1e1428f7f8f72ba2b9a1da7f732ff versionId=null, S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_faixa_etaria/_delta_log/00000000000000000004.json; isDirectory=false; length=1503; replication=1; blocksize=33554432; modification_time=1785647531136; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=0e629bb8c1b89ea411ec8fb2a5b4fead versionId=null, S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_faixa_etaria/_delta_log/00000000000000000005.json; isDirectory=false; length=1503; replication=1; blocksize=33554432; modification_time=1785648470000; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=028627a498aa92fe0885e924f948a6c5 versionId=null),org.apache.spark.sql.delta.EmptyCheckpointProvider$@287b4d2d,1785648470000), checksumOpt=None).
26/08/02 05:27:50 WARN HiveExternalCatalog: Couldn't find corresponding Hive SerDe for data source provider delta. Persisting data source table `spark_catalog`.`gold`.`beneficiarios_por_faixa_etaria` into Hive metastore in Spark SQL specific format, which is NOT compatible with Hive.

  [4/4] CREATE OR REPLACE TABLE gold.beneficiarios_por_municipio USING delta AS SELECT c...

26/08/02 05:27:52 WARN OptimisticTransaction: [tableId=8a9eb749,txnId=c8aa9a22] Change in the table id detected in txn. Table id for txn on table at s3a://lakehouse/gold/beneficiarios_por_municipio was 8a9eb749-121b-4eb2-8a38-e359138990eb when the txn was created and is now changed to 8d583756-f36f-4e15-816e-3861b66ed474.
26/08/02 05:27:52 WARN DeltaLog: Change in the table id detected while updating snapshot.
Previous snapshot = Snapshot(path=s3a://lakehouse/gold/beneficiarios_por_municipio/_delta_log, version=4, metadata=Metadata(8a9eb749-121b-4eb2-8a38-e359138990eb,null,null,Format(parquet,Map()),{"type":"struct","fields":[{"name":"cd_municipio","type":"string","nullable":true,"metadata":{}},{"name":"nm_municipio","type":"string","nullable":true,"metadata":{}},{"name":"qt_beneficiarios_ativos","type":"long","nullable":true,"metadata":{}}]},List(),Map(),Some(1785647531500)), logSegment=LogSegment(s3a://lakehouse/gold/beneficiarios_por_municipio/_delta_log,4,WrappedArray(S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_municipio/_delta_log/00000000000000000000.json; isDirectory=false; length=1480; replication=1; blocksize=33554432; modification_time=1785640157325; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=d36ed61c4b93ad13570b3f43bfb8b749 versionId=null, S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_municipio/_delta_log/00000000000000000001.json; isDirectory=false; length=1643; replication=1; blocksize=33554432; modification_time=1785644797812; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=33a50db8191a42ee1a797a75c22eeaff versionId=null, S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_municipio/_delta_log/00000000000000000002.json; isDirectory=false; length=1643; replication=1; blocksize=33554432; modification_time=1785644907285; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=adb87b24a748b3f92a1efd16bdd67897 versionId=null, S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_municipio/_delta_log/00000000000000000003.json; isDirectory=false; length=1643; replication=1; blocksize=33554432; modification_time=1785646055320; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=4b791fc4213cdff92b4b5185f031e9d2 versionId=null, S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_municipio/_delta_log/00000000000000000004.json; isDirectory=false; length=1643; replication=1; blocksize=33554432; modification_time=1785647532776; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=7609d8ae7edd3cc697b8f88f5ff5db2b versionId=null),org.apache.spark.sql.delta.EmptyCheckpointProvider$@287b4d2d,1785647532776), checksumOpt=None)
New snapshot = Snapshot(path=s3a://lakehouse/gold/beneficiarios_por_municipio/_delta_log, version=5, metadata=Metadata(8d583756-f36f-4e15-816e-3861b66ed474,null,null,Format(parquet,Map()),{"type":"struct","fields":[{"name":"cd_municipio","type":"string","nullable":true,"metadata":{}},{"name":"nm_municipio","type":"string","nullable":true,"metadata":{}},{"name":"qt_beneficiarios_ativos","type":"long","nullable":true,"metadata":{}}]},List(),Map(),Some(1785648471033)), logSegment=LogSegment(s3a://lakehouse/gold/beneficiarios_por_municipio/_delta_log,5,ArrayBuffer(S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_municipio/_delta_log/00000000000000000000.json; isDirectory=false; length=1480; replication=1; blocksize=33554432; modification_time=1785640157325; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=d36ed61c4b93ad13570b3f43bfb8b749 versionId=null, S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_municipio/_delta_log/00000000000000000001.json; isDirectory=false; length=1643; replication=1; blocksize=33554432; modification_time=1785644797812; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=33a50db8191a42ee1a797a75c22eeaff versionId=null, S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_municipio/_delta_log/00000000000000000002.json; isDirectory=false; length=1643; replication=1; blocksize=33554432; modification_time=1785644907285; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=adb87b24a748b3f92a1efd16bdd67897 versionId=null, S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_municipio/_delta_log/00000000000000000003.json; isDirectory=false; length=1643; replication=1; blocksize=33554432; modification_time=1785646055320; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=4b791fc4213cdff92b4b5185f031e9d2 versionId=null, S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_municipio/_delta_log/00000000000000000004.json; isDirectory=false; length=1643; replication=1; blocksize=33554432; modification_time=1785647532776; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=7609d8ae7edd3cc697b8f88f5ff5db2b versionId=null, S3AFileStatus{path=s3a://lakehouse/gold/beneficiarios_por_municipio/_delta_log/00000000000000000005.json; isDirectory=false; length=1643; replication=1; blocksize=33554432; modification_time=1785648472000; access_time=0; owner=root; group=root; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=true; isErasureCoded=false} isEmptyDirectory=FALSE eTag=c7bac854cf6978f8a9e1717290223ef1 versionId=null),org.apache.spark.sql.delta.EmptyCheckpointProvider$@287b4d2d,1785648472000), checksumOpt=None).
26/08/02 05:27:52 WARN HiveExternalCatalog: Couldn't find corresponding Hive SerDe for data source provider delta. Persisting data source table `spark_catalog`.`gold`.`beneficiarios_por_municipio` into Hive metastore in Spark SQL specific format, which is NOT compatible with Hive.

  namespace                       tableName  isTemporary
0      gold  beneficiarios_por_faixa_etaria        False
1      gold     beneficiarios_por_municipio        False
2      gold     beneficiarios_por_operadora        False
3                                   raw_csv        False

## Consultas do case
(a) top 5 operadoras — (b) faixa etária com mais beneficiários — (c) beneficiários por município.

In [5]:
run_queries(spark)

(a) Top 5 operadoras por beneficiários ativos:
+------------+------------------------------------------+-----------------------+
|cd_operadora|nm_razao_social                           |qt_beneficiarios_ativos|
+------------+------------------------------------------+-----------------------+
|359017      |NOTRE DAME INTERMÉDICA SAÚDE S.A.         |4324507                |
|301949      |ODONTOPREV S/A                            |2844728                |
|326305      |AMIL ASSISTÊNCIA MÉDICA INTERNACIONAL S.A.|2671950                |
|006246      |SUL AMERICA COMPANHIA DE SEGURO SAÚDE     |2111707                |
|000582      |PORTO SEGURO - SEGURO SAÚDE S/A           |1391580                |
+------------+------------------------------------------+-----------------------+

(b) Faixa etária com mais beneficiários:
+---------------+-----------------------+
|de_faixa_etaria|qt_beneficiarios_ativos|
+---------------+-----------------------+
|40 a 44 anos   |3100823                |
+---------------+-----------------------+

(c) Beneficiários por município (top 20 de 646 ):
+------------+---------------------+-----------------------+
|cd_municipio|nm_municipio         |qt_beneficiarios_ativos|
+------------+---------------------+-----------------------+
|355030      |São Paulo            |9833635                |
|350950      |Campinas             |1031975                |
|351880      |Guarulhos            |1013731                |
|354870      |São Bernardo do Campo|747368                 |
|354780      |Santo André          |703818                 |
|353440      |Osasco               |603048                 |
|355220      |Sorocaba             |596055                 |
|354990      |São José dos Campos  |581614                 |
|354340      |Ribeirão Preto       |563972                 |
|352590      |Jundiaí              |444951                 |
|354850      |Santos               |377595                 |
|353870      |Piracicaba           |365182                 |
|352940      |Mauá                 |331385                 |
|351380      |Diadema              |307294                 |
|350570      |Barueri              |293487                 |
|354980      |São José do Rio Preto|293269                 |
|353060      |Mogi das Cruzes      |291129                 |
|350160      |Americana            |263637                 |
|351060      |Carapicuíba          |262240                 |
|350600      |Bauru                |231506                 |
+------------+---------------------+-----------------------+
only showing top 20 rows


Resultados salvos em /app/output/